export const SAVE_NAVIGATION = "SAVE_NAVIGATION";
export const SET_CURRENT_SCREEN = "SET_CURRENT_SCREEN";
export const SET_IS_SIGN_IN = "SET_IS_SIGN_IN";
export const SET_URL = "SET_URL";
export const SET_IS_ACTIVE_ADD_ITEM_BTN = "SET_IS_ACTIVE_ADD_ITEM_BTN";
export const SET_CURRENT_VIEWED_ITEM = "SET_CURRENT_VIEWED_ITEM";
export const SET_CART = "SET_CART";
export const SET_FAVORITES = "SET_FAVORITES";
