require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'sarn2' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  pod 'react-native-ble-manager', :path => '../node_modules/react-native-ble-manager'

  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  pod 'react-native-bluetooth-status', :path => '../node_modules/react-native-bluetooth-status'

  pod 'react-native-location', :path => '../node_modules/react-native-location'

  pod 'react-native-settings', :path => '../node_modules/react-native-settings'

  pod 'react-native-connectivity-status', :path => '../node_modules/react-native-connectivity-status'

  target 'sarn2Tests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'sarn2-tvOS' do
  # Pods for sarn2-tvOS

  target 'sarn2-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
